"""alter user table column 

Revision ID: 545af26ef54b
Revises: fd62dc75f12c
Create Date: 2025-06-29 12:45:49.464359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545af26ef54b'
down_revision = 'fd62dc75f12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.String(length=255), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('_password')

    # ### end Alembic commands ###
